#!/usr/bin/env node
/**
 * verify-fresh.mjs — is what is on disk what the generators would produce now?
 *
 * Every generator in this pipeline has a --check mode EXCEPT the bundler step,
 * and that gap is invisible: a stale dist/ serves happily and every downstream
 * gate passes against it, because the gates check dist against the mirror, not
 * dist against src.
 *
 * ⛔ A timestamp is not the judge. Measured: dist/site.js was a day older than
 * src/, which looked like staleness and was not — the regenerated bytes were
 * identical, because the src change (deleting a file nothing imported) could not
 * reach the bundle. The inference from mtime was wrong in the harmless
 * direction; the same inference is available to be wrong in the other one.
 *
 * ⭐ So regenerate and compare BYTES. That is the same discipline
 * slice-modules --check and build-site --check already apply; this closes the
 * one step that lacked it.
 *
 *   node scripts/verify-fresh.mjs
 */
import { readFile, mkdtemp, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

// ⛔ NOT hardcoded. These three paths named one project's shape for several
// releases, which is how a gate ends up FATAL on a port that is merely built
// differently. A whole-site port has NO bundle step at all: it ships the
// packer's own chunks verbatim, and this gate's whole subject is absent.
const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf("--" + n); return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : d; };
const sha = (b) => createHash("sha256").update(b).digest("hex");
const ENTRY = path.resolve(flag("entry", "src/index.js"));
const DIST = path.resolve(flag("dist", "dist/site.js"));
const SERVED = path.resolve(flag("served", "site/_next/static/chunks/site.port.js"));

let fail = 0;
console.log("=== verify-fresh ===");

// ⭐ A gate that examined nothing must SAY it examined nothing. Exiting 0 in
// silence and exiting 0 after checking everything look identical from the
// outside, and only one of them means anything.
if (!existsSync(ENTRY)) {
  console.log(`  note — ${path.relative(process.cwd(), ENTRY)} does not exist, so this port has no bundle step`);
  console.log(`         and nothing for this gate to regenerate. The equivalent coverage for a`);
  console.log(`         verbatim-chunk port is slice-modules --check plus build-site --check.`);
  console.log(`\nSKIPPED — no bundle step in this port. Pass --entry to point at one.`);
  process.exit(0);
}

const tmp = await mkdtemp(path.join(tmpdir(), "fresh-"));
const rebuilt = path.join(tmp, path.basename(DIST));
const r = spawnSync("npx", ["esbuild", ENTRY, "--bundle", "--format=iife", `--outfile=${rebuilt}`], { encoding: "utf8" });
if (r.status !== 0) {
  console.error(`FATAL — rebuilding ${path.relative(process.cwd(), ENTRY)} failed:\n${(r.stderr || "").split("\n").slice(0, 12).join("\n")}`);
  process.exit(5);
}

const now = await readFile(rebuilt);
const disk = await readFile(DIST).catch(() => null);
if (!disk) { fail++; console.log(`  FAIL dist/site.js is missing — run \`npm run src:build\``); }
else if (sha(now) !== sha(disk)) {
  fail++;
  console.log(`  FAIL dist/site.js differs from a fresh build of src/`);
  console.log(`         on disk ${sha(disk).slice(0, 16)}   rebuilt ${sha(now).slice(0, 16)}`);
  console.log(`       src/ changed after the bundle was built. Run \`npm run src:build && npm run build\`.`);
} else console.log(`  ok   dist/site.js is a current build of src/  (${sha(disk).slice(0, 16)})`);

// ⚠ And the served copy must be that same bundle. build-site copies it in, so a
// build-site that was never re-run leaves the OLD bundle being served while
// dist/ is correct — the gap moves one step downstream rather than closing.
const served = await readFile(SERVED).catch(() => null);
if (!served) { fail++; console.log(`  FAIL site/ does not carry the port bundle — run \`npm run build\``); }
else if (disk && sha(served) !== sha(disk)) {
  fail++;
  console.log(`  FAIL the bundle in site/ is not the one in dist/`);
  console.log(`         dist ${sha(disk).slice(0, 16)}   served ${sha(served).slice(0, 16)}`);
  console.log(`       Run \`npm run build\` — the shell build copies dist/ into site/.`);
} else console.log(`  ok   site/ serves exactly the bundle in dist/`);

await rm(tmp, { recursive: true, force: true });
console.log(fail ? `\nFAIL — ${fail} staleness problem(s).` : `\nPASS — src/ -> dist/ -> site/ are in step.`);
process.exit(fail ? 1 : 0);
